// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Default to production values
let SUPABASE_URL = "https://exatcpxfenndpkozdnje.supabase.co";
let SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4YXRjcHhmZW5uZHBrb3pkbmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NjY4MTgsImV4cCI6MjA1NjE0MjgxOH0.8PIDjiIl5xwoo6GoJCqMrFilanV_9EmgtQx_sEvG6as";

// Check if environment variables are available (for development environment)
if (import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_ANON_KEY) {
  console.log('Using development Supabase configuration');
  SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
}

// Export these constants if needed elsewhere
export const SUPABASE_URL_EXPORT = SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY = SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_ANON_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce'
    },
    global: {
      fetch: (url: RequestInfo | URL, options?: RequestInit) => {
        // Log fetch request details for debugging
        console.log('Supabase fetch request:', url.toString());
        
        // In development, log more detailed request information
        if (import.meta.env.DEV) {
          console.log('Supabase request options:', options);
          console.log('Authorization header:', options?.headers ? (options.headers as any)['Authorization'] : 'None');
          console.log('API key header:', options?.headers ? (options.headers as any)['apikey'] : 'None');
          
          // Add a custom header for tracking
          if (options && options.headers) {
            (options.headers as any)['x-debug-info'] = 'enabled';
          }
        }
        
        return fetch(url, options);
      },
    },
  }
);

// Add a function to check if a location exists for a company
export const checkLocationsForCompany = async (companyId: string): Promise<boolean> => {
  console.log(`Checking if company ${companyId} has any locations...`);
  
  try {
    // Make a direct count query instead of fetching all records
    const { count, error } = await supabase
      .from('locations')
      .select('*', { count: 'exact', head: true })
      .eq('company_id', companyId);
    
    if (error) {
      console.error('Error checking locations:', error);
      return false;
    }
    
    console.log(`Found ${count} locations for company ${companyId}`);
    return count !== null && count > 0;
  } catch (e) {
    console.error('Exception checking locations:', e);
    return false;
  }
};

// Function to create a temporary JWT for API access when anonymous auth is disabled
export const createTemporaryAuthToken = async (clerkToken?: string): Promise<string | null> => {
  try {
    // If we have a Clerk token, we could use it, but for now let's just use the API key
    // as a simple solution that doesn't rely on the Clerk getToken() method
    
    console.log('Using API key authentication as fallback');
    return SUPABASE_ANON_KEY;
  } catch (error) {
    console.error('Error creating temporary auth token:', error);
    return null;
  }
};
