// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exatcpxfenndpkozdnje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4YXRjcHhmZW5uZHBrb3pkbmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NjY4MTgsImV4cCI6MjA1NjE0MjgxOH0.8PIDjiIl5xwoo6GoJCqMrFilanV_9EmgtQx_sEvG6as";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);